spring:
  rabbitmq:
    host: localhost
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: 5672
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/meowlopedb}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: authservice
service:
  rabbitmq:
    routing-key:
      user-info: userInfoRoutingKey
    exchange:
      user-info: userInfoExchange
  jwt:
    secret: ${JWT_SECRET_KEY:secretkey123}
    refresh:
      expirationDays: 14
    access:
      expirationMinutes: 15
server:
  port: 8082
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health, info