services:
  service-discovery:
    build:
      context: service-discovery
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://localhost:8761/eureka
    ports:
      - "8761:8761"
    networks:
      - meowlope-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 15s
    restart: unless-stopped

  api-gateway:
    build:
      context: api-gateway
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery:8761/eureka
    ports:
      - "8765:8765"
    networks:
      - meowlope-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8765/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 15s
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-discovery:
        condition: service_healthy

  user-service:
    build:
      context: user-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery:8761/eureka
    ports:
      - "8081:8081"
    networks:
      - meowlope-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 15s
    restart: unless-stopped
    depends_on:
      api-gateway:
        condition: service_healthy

  auth-service:
    build:
      context: auth-service
    env_file:
      - ./auth-service/.env
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/meowlopedb
    ports:
      - "8082:8082"
    networks:
      - meowlope-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 15s
    restart: unless-stopped
    depends_on:
      api-gateway:
        condition: service_healthy
      postgres:
        condition: service_healthy

  postgres:
    container_name: Postgres
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - meowlope-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13.0-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - meowlope-net
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq'
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:

networks:
  meowlope-net:
    driver: bridge
