services:
  service-discovery:
    build:
      context: service-discovery
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://localhost:8761/eureka
    ports:
      - "8761:8761"
    networks:
      - meowlope-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 15s
    restart: on-failure

  api-gateway:
    build:
      context: api-gateway
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery:8761/eureka
    ports:
      - "8765:8765"
    networks:
      - meowlope-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8765/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 15s
    restart: on-failure
    depends_on:
      service-discovery:
        condition: service_healthy

  user-service:
    build:
      context: user-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery:8761/eureka
    ports:
      - "8081:8081"
    networks:
      - meowlope-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 15s
    restart: on-failure
    depends_on:
      api-gateway:
        condition: service_healthy

networks:
  meowlope-net:
    driver: bridge