spring:
  application:
    name: apigateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: GET, POST, PUT, DELETE, OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: userservice_route
          uri: lb://userservice
          predicates:
            - Path=/tests/**
        - id: authservice_route
          uri: lb://authservice
          predicates:
            - Path=/api/v1/auth/**

server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health