spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: userservice_route
          uri: lb://userservice
          predicates:
            - Path=/tests/**
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka