spring:
  rabbitmq:
    host: localhost
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: 5672
  application:
    name: userservice
server:
  port: 8081
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health
service:
  rabbitmq:
    routing-key:
      user-info: userInfoRoutingKey
    exchange:
      user-info: userInfoExchange
